name: Dungeoner
version: @version@
main: net.rikusen.dungeoner.Dungeoner
api-version: 1.16
authors: [ rikusen0335 ]
#depend:
#  - CustomStructures
commands:
  dungeon:
    description: The command you used

  rpg:
    description: For an RPG system

  item:
    description: For an Item system